CREATE OR REPLACE PROCEDURE TEST_PROCEDURE1 AS
BEGIN
  DBMS_OUTPUT.PUT_LINE('YOU HAVE EXECUTED PROCEDURE 1…');
END;


CREATE OR REPLACE PROCEDURE TEST_PROCEDURE2 AS
BEGIN
  DBMS_OUTPUT.PUT_LINE('YOU HAVE EXECUTED PROCEDURE 2…');
END;


CREATE OR REPLACE PROCEDURE run_test(test_id  IN NUMBER DEFAULT 1) AS
  sql_text  VARCHAR2(200);
BEGIN
  sql_text := 'BEGIN ' ||
              '  TEST_PROCEDURE' || test_id || '; ' ||
              'END;';

  EXECUTE IMMEDIATE sql_text;

END;
/